name: zxcvbn
version: 2.0.0
description: Dart port of DropBox's zxcvbn library.
homepage: https://github.com/careapp-inc/zxcvbn-dart
repository: https://github.com/careapp-inc/zxcvbn-dart

dev_dependencies:
  test: any
environment:
  sdk: '>=3.9.0 <4.0.0'
